#!/usr/bin/env bash
# Install Nginx
apt-get update
apt-get install -y nginx

# Create a default HTML page with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Make sure Nginx is listening on port 80
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

# Restart Nginx
/etc/init.d/nginx restart
