#!/bin/bash

# Update the system
sudo apt update
sudo apt upgrade -y

# Install Nginx if not already installed
sudo apt install -y nginx

# Create a configuration file for the redirect
echo "server {
    listen 80;
    100.26.154.118;
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/sites-available/redirect_me

# Create a symbolic link to enable the configuration
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply the changes
sudo systemctl reload nginx

# Restart Nginx to ensure the configuration takes effect
sudo systemctl restart nginx
