#!/usr/bin/env bash
#to create a script that uses if, else if and else statements
p=1
while [ $p -le 10 ]
do
	if [ $p -eq 4 ]
	then
	    echo "bad luck"
	elif [ $p -eq 8 ]
	then
	    echo "good luck"
       	else
	    echo "Best School"
	fi
	((x++))
done
