#!/usr/bin/env bash
#to create a script that uses case statements
p=1
while [ $p -le 20 ]
do
    echo "$p"
    case $p in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((p++))
done
