#!/usr/bin/env bash

# Configure Nginx to run as the nginx user and listen on port 8080

# Replace the default Nginx configuration file with a new one
mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.backup
cat << 'EOF' > /etc/nginx/nginx.conf
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /var/run/nginx.pid;

events {
    worker_connections 768;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    server {
        listen 8080 default_server;
        listen [::]:8080 default_server;

        root /var/www/html;
        index index.html;

        server_name _;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
EOF

# Restart Nginx to apply the changes
service nginx restart

# Check if Nginx is running as the nginx user
ps aux | grep 'nginx: master process' | grep -v grep

# Check if Nginx is listening on port 8080
nc -z 0 8080
